pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SONAR-CLOUD'
    organization: 'devops-fundamental-v4'
    scannerMode: 'Other'
    projectKey: Devops-fundamental-v4_java-web-1
    projectName: java-web-1
  displayName: 'SonarCloud'
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false
