pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
  displayName: Build
   
   

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SONAR-CLOUD'
    organization: 'devops-fundamental-v4'
    projectKey: Devops-fundamental-v4_java-web-1
    projectName: java-web-1
  displayName: 'SonarCloud'
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false
- task: Docker@2
  inputs:
    containerRegistry: 'docker-service'
    command: 'login'
    